-- ------------------------------------------------ -------
-- AUTOR : NTTDATA CENTERS - SEVILLA     
-- DESCRIPCIÓN : JAVA - JDBC - MYSQL - PANDEMIA
-- RESPONSABLE : SALESIANAS Mª AUXILIADORA
-- ------------------------------------------------ -------


--Inserciones a la tabla Distribuidor_Vacuna --

INSERT INTO DISTRIBUIDOR_VACUNA VALUES('DV1', 'CV1', 'ASTRA ZENECA');
INSERT INTO DISTRIBUIDOR_VACUNA VALUES('DV1', 'CV3', 'ASTRA ZENECA');
INSERT INTO DISTRIBUIDOR_VACUNA VALUES('DV2', 'CV2', 'PFIZER');
INSERT INTO DISTRIBUIDOR_VACUNA VALUES('DV2', 'CV5', 'PFIZER');
INSERT INTO DISTRIBUIDOR_VACUNA VALUES('DV3', 'CV1', 'JANSSEN');
INSERT INTO DISTRIBUIDOR_VACUNA VALUES('DV3', 'CV4', 'JANSSEN');
INSERT INTO DISTRIBUIDOR_VACUNA VALUES('DV4', 'CV3', 'MODERNA');
INSERT INTO DISTRIBUIDOR_VACUNA VALUES('DV4', 'CV4', 'MODERNA');
INSERT INTO DISTRIBUIDOR_VACUNA VALUES('DV5', 'CV5', 'NOVAVAX');
INSERT INTO DISTRIBUIDOR_VACUNA VALUES('DV5', 'CV2', 'NOVAVAX');
