---------------------------------------------------------
-- AUTOR       : NTTDATA CENTERS - SEVILLA     
-- DESCRIPCIÓN : JAVA - JDBC - MYSQL - PANDEMIA
-- RESPONSABLE : SALESIANAS Mª AUXILIADORA
---------------------------------------------------------

-- Creación de tabla Distribuidor de Vacunas.
CREATE TABLE PANDEMIA.DISTRIBUIDOR_VACUNA (ID_VACUNA INT (6), ID_CENTRO INT(6), NOMBRE VARCHAR (30),PRIMARY KEY (ID_VACUNA, ID_CENTRO), FOREIGN KEY (ID_CENTRO) REFERENCES PANDEMIA.CENTRO_VACUNACION(ID_CENTRO));

-- Insercción de datos de Distribuidor de Vacunas.

INSERT INTO DISTRIBUIDOR_VACUNA VALUES(1, 1, "ASTRA ZENECA");
INSERT INTO DISTRIBUIDOR_VACUNA VALUES(1, 3, "ASTRA ZENECA");
INSERT INTO DISTRIBUIDOR_VACUNA VALUES(2, 2, "PFIZER");
INSERT INTO DISTRIBUIDOR_VACUNA VALUES(2, 5, "PFIZER");
INSERT INTO DISTRIBUIDOR_VACUNA VALUES(3, 1, "JANSSEN");
INSERT INTO DISTRIBUIDOR_VACUNA VALUES(3, 4, "JANSSEN");
INSERT INTO DISTRIBUIDOR_VACUNA VALUES(4, 3, "MODERNA");
INSERT INTO DISTRIBUIDOR_VACUNA VALUES(4, 4, "MODERNA");
INSERT INTO DISTRIBUIDOR_VACUNA VALUES(5, 5, "NOVAVAX");
INSERT INTO DISTRIBUIDOR_VACUNA VALUES(5, 2, "NOVAVAX");