---------------------------------------------------------
-- AUTOR       : NTTDATA CENTERS - SEVILLA     
-- DESCRIPCIÓN : JAVA - JDBC - MYSQL - PANDEMIA
-- RESPONSABLE : SALESIANAS Mª AUXILIADORA
---------------------------------------------------------

-- Creación de tabla Hospitalizaciones.
CREATE TABLE PANDEMIA.HOSPITALIZACIONES ( ID_RECUENTO_HOS INT (8) AUTO_INCREMENT, CAMAS_OCUPADAS INT (11), FECHA DATE, ID_CIUDAD INT (6), PRIMARY KEY (ID_RECUENTO_HOS, ID_CIUDAD), FOREIGN KEY (ID_CIUDAD) REFERENCES PANDEMIA.CIUDAD(ID_CIUDAD));

-- Insercción de datos de Hospitalizaciones.

INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(200, '2020-08-25', 1);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(220, '2020-09-25', 1);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(400, '2020-10-25', 1);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(150, '2020-11-25', 1);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(200, '2020-08-25', 2);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(220, '2020-09-25', 2);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(480, '2020-10-25', 2);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(100, '2020-11-25', 2);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(200, '2020-08-25', 3);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(260, '2020-09-25', 3);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(500, '2020-10-25', 3);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(100, '2020-11-25', 3);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(200, '2020-08-25', 4);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(210, '2020-09-25', 4);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(80, '2020-10-25', 4);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(1000, '2020-11-25', 4);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(120, '2020-08-25', 5);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(110, '2020-09-25', 5);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(100, '2020-10-25', 5);
INSERT INTO HOSPITALIZACIONES(CAMAS_OCUPADAS, FECHA, ID_CIUDAD) VALUES(110, '2020-11-25', 5);



