---------------------------------------------------------
-- AUTOR       : NTTDATA CENTERS - SEVILLA     
-- DESCRIPCIÓN : JAVA - JDBC - MYSQL - PANDEMIA
-- RESPONSABLE : SALESIANAS Mª AUXILIADORA
---------------------------------------------------------

-- Creación de tabla Vacunaciones.
CREATE TABLE PANDEMIA.VACUNACIONES ( ID_RECUENTO_VAC INT (8) AUTO_INCREMENT, VACUNACIONES_TOTALES INT (11), FECHA DATE, ID_CIUDAD INT (6), PRIMARY KEY (ID_RECUENTO_VAC, ID_CIUDAD), FOREIGN KEY (ID_CIUDAD) REFERENCES PANDEMIA.CIUDAD(ID_CIUDAD));

-- Insercción de datos de Vacunaciones.

INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(207, '2020-08-25', 1);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(221, '2020-09-25', 1);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(357, '2020-10-25', 1);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(1224, '2020-11-25', 1);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(205, '2020-08-25', 2);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(229, '2020-09-25', 2);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(489, '2020-10-25', 2);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(1567, '2020-11-25', 2);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(202, '2020-08-25', 3);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(269, '2020-09-25', 3);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(542, '2020-10-25', 3);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(1369, '2020-11-25', 3);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(205, '2020-08-25', 4);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(234, '2020-09-25', 4);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(353, '2020-10-25', 4);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(2080, '2020-11-25', 4);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(120, '2020-08-25', 5);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(204, '2020-09-25', 5);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(345, '2020-10-25', 5);
INSERT INTO VACUNACIONES(VACUNACIONES_TOTALES, FECHA, ID_CIUDAD) VALUES(895, '2020-11-25', 5);